version: '3'

services:
  next-app:
    container_name: frontendDEV
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile

    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    # volumes:
    #   - ./frontend:/app
    restart: always
    ports:
      - 4000:4000
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - .env
    # volumes:
    #   - ./backend:/backend
    restart: always
    ports:
      - 3000:3000