version: '3.7'
services:
  nginx:
    build:
      context: ./nginx/
    container_name: nginx
    ports:
      - "80:8080"
      # - "443:443"
    volumes:
      # - ./v1:/var/www/old_website
      - ./nginx:/etc/nginx/conf.d
      # - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend:rw
      - node_modules:/frontend/node_modules/
    expose: ["3000"]
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      
volumes:
  node_modules: